version: '3.8'

services:
  react-demo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - react-demo-network

  # 可选：添加 nginx 反向代理（生产环境推荐）
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - react-demo
  #   networks:
  #     - react-demo-network

networks:
  react-demo-network:
    driver: bridge

# 可选：添加数据卷（如果需要持久化数据）
# volumes:
#   app-data:
